Add the ability for caches to use a local site redirector
opensciencegrid/docker-xcache pull request #61
Opened 2020-12-15 22:19 UTC by brianhlin

A feature for @Mansalu since his CMS XCache container doesn't yet have a site redirector so there's some noise in his logs

2020-12-15 22:40 UTC, efajardo requested changes
Some minor changes in language and the ability to have multiple redirectors like we do in SoCAL

2020-12-15 22:40 UTC, efajardo commented on atlas-xcache/README.md
> +To configure your cache to make use of a local site redirector, set the following environment variables in the same file
```suggestion
To configure your cache in clustered mode to make use of a cache redirector, set the following environment variables in the same file
```

2020-12-15 22:40 UTC, efajardo commented on atlas-xcache/README.md
> +- `XC_REDIRECTOR_FQDN`: the hostname of your local site redirector
```suggestion
- `XC_REDIRECTOR_FQDN`: the hostname of your local cache redirector.
```

2020-12-15 22:40 UTC, efajardo commented on xcache/xrootd/10-docker-env-var.cfg
> +all.manager $REDIRECTOR_FQDN+ $REDIRECTOR_PORT
```suggestion
set REDIRECTOR_FQDN1=$XC_REDIRECTOR_FQDN
set REDIRECTOR_PORT1=$XC_REDIRECTOR_PORT
all.manager $REDIRECTOR_FQDN1 $REDIRECTOR_PORT1
all.manager $REDIRECTOR_FQDN2 $REDIRECTOR_PORT2

```

2020-12-15 22:40 UTC, efajardo commented on xcache/xrootd/10-docker-env-var.cfg
> +all.manager $REDIRECTOR_FQDN+ $REDIRECTOR_PORT
This sets up for the use of high availability redirectors. Like we do in SoCAL

2020-12-16 19:44 UTC, brianhlin commented
@efajardo would anyone ever run more than 2 HA redirectors?

2020-12-16 20:03 UTC, efajardo commented
@brianhlin I don't think so. Maybe if data lakes take over people will wanter over redundancy in four or five years. So I think assume two at most is valid.

2020-12-17 17:07 UTC, brianhlin commented
@efajardo I went a slightly different route

2020-12-21 22:25 UTC, efajardo approved these changes
It looks good.

2020-12-21 23:05 UTC, merged

2020-12-21 23:29 UTC, Mansalu commented
Hooray